config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create, :edit, :update]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :about, presence: true, uniqueness: true
  validates :method, presence: true, uniqueness: true

  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktail_controller.rb
class CocktailController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def show
    @ingredient = Ingredient.new
  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail), notice: "Cocktail Updated"
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy

    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :about, :method, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :edit, :update]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.ingredient = Ingredient.find(params[:dose][:ingredient]) unless params[:dose][:ingredient].blank?
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @dose.update(dose_params)
      redirect_to cocktail_path(@cocktail), notice: "Dosage Updated"
    else
      render :edit
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_card.html.erb
<div class = "container">
  <div class="wrapper">
    <div class="cards">
      <% @cocktails.each do |cocktail| %>
        <figure class="card">
            <%= cl_image_tag cocktail.photo.key, alt: "alttext" %>
            <figcaption><%= link_to cocktail.name, cocktail_path(cocktail), style: "color:white; text-decoration:none;"%></figcaption>
        </figure>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/_form.html.erb
<div class="form-container" >
  <%= simple_form_for [@cocktail] do |f| %>
    <%= f.input :name, placeholder: 'Name' %>
    <%= f.input :about, placeholder: 'About' %>
    <%= f.input :method, placeholder: 'Method' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add Cocktail", class: "btn btn-primary"%>
    <%= link_to "Go back", cocktails_path, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<%= render 'shared/nav_affix' %>
<br>
<br>
<br>
<div class="container">
  <div class="form-container">
    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.error_notification %>
      <h1>Cocktail Name</h1>
      <%= f.input :name, label: false %>

      <h1>About</h1>
      <%= f.input :about, label: false %>

      <h1>Method</h1>
      <%= f.input :method, label: false, :input_html => {:rows => 10} %>
      <%= f.button :submit, class: "btn btn-primary" %>
      <%= link_to "Delete Cocktail", cocktail_path(@cocktail), method: :delete, class: "btn btn-danger", :data => {:confirm => "Are You Sure?"} %>
      <%= link_to "Cancel", request.referer.present? ? request.referer : root_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cocktails/index.html.erb
<%= render 'shared/navbar' %>
<div id="hero">
  <%= video_tag "video.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>

  <div class="caption">
    <p>________________________________</p>
    <h1 class="hero-h1">The Cocktail Experience</h1>
    <h2 class="hero-h2">Living every hour like it’s happy hour</h2>
    <p class="underscore-flip">________________________________</p>
  </div>

</div>

<br>
<!-- <form onsubmit="event.preventDefault();" role="search">
  <label for="search">Search</label>
  <input id="search" type="search" placeholder="Search..." autofocus required />
  <button type="submit">Go</button>
</form> -->
<h1 class="drinks-header">THE SIGNATURES</h1>
<p class="caption underscore-flip">_______________________________________________________________________________________________</p>
<%= render 'card' %>
<%= render 'shared/footer' %>

app/views/cocktails/new.html.erb
<%= render 'shared/nav_affix' %>
<br>
<br>
<br>
<br>
<div class="container">
  <h1>Add Cocktail</h1>
  <hr style="width:43%; float:left;">
  <%= render 'cocktails/form'%>
</div>

app/views/cocktails/show.html.erb
<%= render 'shared/nav_affix'%>

<div class="container">
<br>
<br>
<br>
  <div class="left-column">
    <div class="show-cards">
      <br>
      <h1><%= @cocktail.name %></h1>
      <figure class="card">
          <%= cl_image_tag @cocktail.photo.key, alt: "alttext" %>
      </figure>
      <p><%= @cocktail.about %></p>
    </div>
  </div>
  <div class="right-column">
    <br>
    <br>
    <div class="container">
      <h3 style="text-align: center;">Ingredients</h3>
      <hr>
      <% @cocktail.doses.each do |d| %>
        <ul style="list-style-type:none; padding: 0; text-align: center">
          <li>
            <%= d.ingredient.name %> :
            <%= d.description %> |
            <%= link_to "Delete", dose_path(d), method: :delete,
            data: { confirm: "Are you sure?" } %>
          </li>
        </ul>
      <% end %>
      <br>
      <div class="button-container">
        <div class="button-center">
          <%= link_to "Add Ingredient",  new_cocktail_dose_path(@cocktail), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="container">
      <h3 style="text-align: center;">Method</h3>
      <hr>
      <ul style="list-style-type:none; padding: 0; text-align: center">
        <li><%= h(@cocktail.method).gsub(/\n/, '<br/>').html_safe %></li>
      </ul>
    </div>
    <br>
    <div class="button-container">
      <div class="button-center">
        <%= link_to "Edit/Delete Cocktail", edit_cocktail_path(@cocktail), class: 'btn btn-primary' %>
        <%= link_to "Go Back", cocktails_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/doses/new.html.erb
<%= render 'shared/nav_affix' %>
<br>
<br>
<br>
<br>
<div class="container">
  <h1>Add your ingredients</h1>

  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.input :ingredient_id, collection: Ingredient.order(:name) %>
    <%= f.input :description, label: 'Add the quantity', as: :text %>
    <%= f.submit "Add ingredient", value: 'Add Ingredient', class: "btn btn-primary"%>
    <%= link_to "Go Back", cocktail_path(@cocktail), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <h2>Add your ingredients</h2>

  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <div class="row">
      <div class="col">
        <%= f.input :alcohol_id, collection: Alcohol.order(:name), as: :check_boxes %>
      </div>

      <div class="col">
        <%= f.input :mixer_id, collection: Mixer.order(:name), as: :check_boxes %>
      </div>

      <div class="col">
        <%= f.input :garnish_id, collection: Garnish.order(:name), as: :check_boxes %>
      </div>
    </div>

    <%= f.input :method, label: 'Add the method', as: :text%>
    <%= f.submit "Add ingredients", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Cocktail Experience</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer-dark">
  <div class="container">
    <div class="row">
        <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
    </div>
    <p class="copyright">The Cocktail Experience © 2021</p>
  </div>
</footer>

app/views/shared/_nav_affix.html.erb
<nav class="nav-fixed">
  <div class="container">
      <div class="logo">
        <%= link_to 'The Cocktail Experience', cocktails_path %>
      </div>
      <div id="mainListDiv" class="main_list">
        <ul class="navlinks">
          <li><%= link_to 'Add New Cocktail', new_cocktail_path %></li>
        </ul>
      </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="nav">
  <div class="container">
      <div class="logo">
        <%= link_to 'The Cocktail Experience', cocktails_path %>
      </div>
      <div id="mainListDiv" class="main_list">
        <ul class="navlinks">
          <li><%= link_to 'Add New Cocktail', new_cocktail_path %></li>
        </ul>
      </div>
  </div>
</nav>

<!-- Jquery needed -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Function used to shrink nav bar removing paddings and adding black background -->
<script>
  $(window).scroll(function() {
    if ($(document).scrollTop() > 50) {
        $('.nav').addClass('affix');
        console.log("OK");
    } else {
        $('.nav').removeClass('affix');
    }
  });
</script>